version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: chatty-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chatty
      MYSQL_USER: user
      MYSQL_PASSWORD: ChattyPro.2025
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
